//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerTable
    {
        public string Name { get; set; }
        public string cnic { get; set; }
        public string email { get; set; }
        public string contnumber { get; set; }
        public string city { get; set; }
        public string id { get; set; }
    }
}
