//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public string Contact_Number { get; set; }
        public string City { get; set; }
        public string E_mail { get; set; }
        public string Collection_Name { get; set; }
    }
}
